apiVersion: v1
kind: Service
metadata:
  name: pet-clinic-cicd
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: pet-clinic-cicd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-clinic-cicd
  template:
    metadata:
      labels:
        app: pet-clinic-cicd
    spec:
      containers:
        - name: pet-clinic-cicd
          image: CONTAINER_IMAGE
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80